# SMB multi-customer example
[linux:children]
lab
customer_alpha_linux

[lab]
# lab1 ansible_host=192.168.56.10 ansible_user=ansible

[customer_alpha_linux]
# app1 ansible_host=10.10.10.11 ansible_user=ansible
# db1  ansible_host=10.10.10.12 ansible_user=ansible

[customer_alpha_linux:vars]
customer_code=alpha
