#!/usr/bin/env python3
"""Materialize the patch calendar for a month into generated job files.

Usage:
  patch_materialize_month.py                 # current month
  patch_materialize_month.py --year 2026 --month 7
  patch_materialize_month.py --also-next     # current + next month

Writes:
  generated/YYYY-MM.json          full job list
  generated/YYYY-MM-jobs/*.job    one file per job (for humans/cron debugging)
  schedule/active_jobs.conf       pipe file consumed by daily runner (all near-term jobs)
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import date
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

from patch_calendar_lib import load_calendar, materialize_jobs  # noqa: E402

CAL_PATH = SCRIPT_DIR / "patch_calendar.yaml"
GEN_DIR = SCRIPT_DIR / "generated"
SCHED_DIR = SCRIPT_DIR / "schedule"
ACTIVE = SCHED_DIR / "active_jobs.conf"


def write_month(year: int, month: int, cal: dict) -> list:
    jobs = materialize_jobs(cal, year, month)
    month_dir = GEN_DIR / f"{year:04d}-{month:02d}-jobs"
    if month_dir.exists():
        for p in month_dir.glob("*.job"):
            p.unlink()
    else:
        month_dir.mkdir(parents=True, exist_ok=True)

    serial = []
    for j in jobs:
        item = {
            "id": j.id,
            "name": j.name,
            "inventory_group": j.inventory_group,
            "patch_date": j.patch_date.isoformat(),
            "patch_time": j.patch_time,
            "window": j.window,
            "recipients": j.recipients,
            "owners_text": j.owners_text,
            "tier": j.tier,
            "notes": j.notes,
            "source": j.source,
            "enabled": j.enabled,
        }
        serial.append(item)
        job_path = month_dir / f"{j.patch_date.isoformat()}_{j.patch_time.replace(':','')}_{j.inventory_group}_{j.id}.job"
        job_path.write_text(json.dumps(item, indent=2) + "\n")

    out_json = GEN_DIR / f"{year:04d}-{month:02d}.json"
    out_json.write_text(json.dumps({"year": year, "month": month, "jobs": serial}, indent=2) + "\n")
    print(f"Wrote {out_json} ({len(serial)} jobs)")
    for j in jobs:
        print(f"  {j.patch_date} {j.patch_time}  {j.inventory_group:12}  {j.name:22}  rcpt={len(j.recipients)}  [{j.source}]")
    return serial


def rebuild_active(months: list[tuple[int, int]], cal: dict) -> None:
    """Union of materialized jobs for given months → active_jobs.conf"""
    mode = cal.get("mode") or {}
    testing = bool(mode.get("testing", False))
    allow_ids = set(mode.get("allow_job_ids") or [])
    notify_only = bool(mode.get("notify_only", False))

    lines = [
        "# AUTO-GENERATED by patch_materialize_month.py — do not edit",
        "# group|patch_date|patch_time|recipients|enabled|job_id|name|notify_only",
        f"# mode.testing={testing} allow_job_ids={sorted(allow_ids)} notify_only={notify_only}",
    ]
    all_jobs = []
    for y, m in months:
        all_jobs.extend(materialize_jobs(cal, y, m))
    all_jobs.sort(key=lambda j: (j.patch_date, j.patch_time, j.inventory_group))
    enabled_count = 0
    for j in all_jobs:
        rcpt = ",".join(j.recipients)
        en = bool(j.enabled and j.recipients)
        if testing:
            # In testing mode only explicitly allowed job IDs stay active
            en = en and (j.id in allow_ids)
        en_s = "yes" if en else "no"
        if en:
            enabled_count += 1
        no_s = "yes" if notify_only else "no"
        lines.append(
            f"{j.inventory_group}|{j.patch_date.isoformat()}|{j.patch_time}|{rcpt}|{en_s}|{j.id}|{j.name}|{no_s}"
        )
    ACTIVE.write_text("\n".join(lines) + "\n")
    print(f"Wrote {ACTIVE} ({len(all_jobs)} entries, enabled={enabled_count}, testing={testing})")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--year", type=int)
    ap.add_argument("--month", type=int)
    ap.add_argument("--also-next", action="store_true")
    ap.add_argument("--calendar", default=str(CAL_PATH))
    args = ap.parse_args()

    today = date.today()
    year = args.year or today.year
    month = args.month or today.month

    GEN_DIR.mkdir(parents=True, exist_ok=True)
    SCHED_DIR.mkdir(parents=True, exist_ok=True)

    cal = load_calendar(args.calendar)
    months = [(year, month)]
    if args.also_next:
        if month == 12:
            months.append((year + 1, 1))
        else:
            months.append((year, month + 1))

    for y, m in months:
        write_month(y, m, cal)
    rebuild_active(months, cal)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
