---
- name: Reset Solaris 5.10 Password
  hosts: solaris_hosts
  become: yes
  become_method: su
  become_user: root
  gather_facts: no
  vars_prompt:
    - name: "target_user"
      prompt: "Enter the username to change password"
      private: no

    - name: "new_password"
      prompt: "Enter the NEW password"
      private: yes

  tasks:
    - name: Transfer and execute password reset script
      ansible.builtin.script:
        cmd: "reset_pass.sh {{ target_user }} {{ new_password }}"
      no_log: true

